# Config Options for StaffChatX
options:
  # Should staff chat messages also be sent to console?
  log to console: true
  
  # If "log to console" is "true", what channel should console be in?
  # Channels must use the IDs in the options below
  # Leave it blank for all channels
  console channel: ""
  
  # Chat Prefix
  # This is used when Staff Chat is toggled for automatic mode
  # Leave it blank to not require a prefix
  prefix: ""
  
  # This is the format used for the default channel
  default format: "&5&lStaffChat &8&l\u00BB &a[{username}] &7&o{message}"
  


# Channel Configuration for StaffChatX
channels:
  # The name of this channel is `channel1`
  # Make sure it's unique for each channel
  channel1:
    # This is the permission required to use the channel
    permission: "staffchatx.channel.mod"
    
    # This is the chat format for players in the channel
    format: "&5&lStaffChat &5&l[&dMod&5&l] &8&l\u00BB &a[{username}] &7&o{message}"
    
  channel2:
    permission: "staffchatx.channel.admin"
    format: "&5&lStaffChat &4&l[&cAdmin&4&l] &8&l\u00BB &a[{username}] &7&o{message}"

  
# Messages and Formatting for StaffChatX
messages:
  no permission: "&c&oYou are not allowed to do that!"
  not player: "&cThis command can only be executed by a Player."
  invalid channel: "&cCould not find channel named '&a{channelName}&c'."
  
  command:
    usage: |-
      &f&lProper Usage:&r
      - /<command> reload
      - /<command> ts/togglesend <off/channel>
      - /<command> tv/toggleview <channel>
      - /<command> send <channel> <message...>
  
    reloaded: "&6The config.yml file for StaffChatX has been reloaded"
    
    toggleview:
      enabled: "&aYou are now viewing the channel &c&o{channelName}&a."
      disabled: "&aYou will no longer see any messages from the channel &c&o{channelName}&a."
      console default: "&aYou are now viewing all channels."
    
    togglesend:
      channel: "&aYou are now sending messages to channel &c&o{channelName}&a."
      disabled: "&cYou have disabled your staff chat."
