name: StaffChatX
main: com.SirBlobman.staffchatx.bungee.StaffChatX
version: 0.0.7
api-version: 1.13
description: Do your staff need privacy?

commands:
  staffchat:
    aliases: [sc, scx, staffchatx]
    description: All commands related to staff chat (reload, toggle, send message)
    usage: |-
      /<command> reload
      OR /<command> toggle
      OR /<command> toggleview
      OR /<command> <message...>