name: "${bukkit.plugin.name}"
main: "${bukkit.plugin.mainClass}"
version: "${bukkit.plugin.version}"
description: "${bukkit.plugin.description}"
author: "SirBlobman"

commands:
  staffchatx:
    aliases: [sc, scx, staffchat]
    description: All commands related to staff chat (reload, toggle, send message)
    usage: "/<command>"