name: StaffChatX
main: com.SirBlobman.staffchatx.StaffChatX
version: 0.0.4
description: Do your staff need privacy?
commands:
  staffchat:
    aliases: [sc, scx, staffchatx]
    description: All commands related to staff chat (reload, toggle, send message)
    usage: |-
      /<command> reload
      OR /<command> toggle
      OR /<command> <message...>